
import os
import shutil
import pandas as pd

def perform_hard_mining():
    # File generated by verify_misclassification.py
    csv_path = 'false_positives.csv'
    
    if not os.path.exists(csv_path):
        print(f"Error: {csv_path} not found. Run verify_misclassification.py first.")
        return

    df = pd.read_csv(csv_path)
    misclassified_images = df['image'].tolist()
    
    source_dir = 'dataset/Forest Fire Dataset kaggle/Testing'
    target_dir = 'dataset/Training/No_Fire'
    
    print(f"Moving {len(misclassified_images)} hard negatives to {target_dir}...")
    
    moved_count = 0
    for img_name in misclassified_images:
        src = os.path.join(source_dir, img_name)
        dst = os.path.join(target_dir, f"hard_negative_{img_name}")
        
        try:
            if os.path.exists(src):
                shutil.copy2(src, dst) # Copy instead of move for safety
                moved_count += 1
                print(f"Copied: {img_name} -> {dst}")
            else:
                print(f"Warning: Source file {src} not found.")
        except Exception as e:
            print(f"Error processing {img_name}: {e}")
            
    print(f"\nSuccessfully moved {moved_count} images for retraining.")

if __name__ == "__main__":
    perform_hard_mining()
